[versions]
agp = "8.13.2"
animation = "1.10.2"
desugar_jdk_libs = "2.1.5"
digitalInkRecognition = "19.0.0"
inkAuthoring = "1.0.0-beta02"
inputMotionprediction = "1.0.0"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.0"
composeBom = "2025.11.01"
lifecycleViewmodelCompose = "2.10.0"
materialIconsExtended = "1.7.8"
okhttpBom = "5.3.2"

[libraries]
androidx-compose-animation = { module = "androidx.compose.animation:animation", version.ref = "animation" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-ink-authoring = { module = "androidx.ink:ink-authoring", version.ref = "inkAuthoring" }
androidx-ink-authoring-compose = { module = "androidx.ink:ink-authoring-compose", version.ref = "inkAuthoring" }
androidx-ink-brush = { module = "androidx.ink:ink-brush", version.ref = "inkAuthoring" }
androidx-ink-brush-compose = { module = "androidx.ink:ink-brush-compose", version.ref = "inkAuthoring" }
androidx-ink-geometry = { module = "androidx.ink:ink-geometry", version.ref = "inkAuthoring" }
androidx-ink-geometry-compose = { module = "androidx.ink:ink-geometry-compose", version.ref = "inkAuthoring" }
androidx-ink-nativeloader = { module = "androidx.ink:ink-nativeloader", version.ref = "inkAuthoring" }
androidx-ink-rendering = { module = "androidx.ink:ink-rendering", version.ref = "inkAuthoring" }
androidx-ink-storage = { module = "androidx.ink:ink-storage", version.ref = "inkAuthoring" }
androidx-ink-strokes = { module = "androidx.ink:ink-strokes", version.ref = "inkAuthoring" }
androidx-input-motionprediction = { module = "androidx.input:input-motionprediction", version.ref = "inputMotionprediction" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
digital-ink-recognition = { module = "com.google.mlkit:digital-ink-recognition", version.ref = "digitalInkRecognition" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttpBom" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

